### ISSUE TITLE
Problem when using Postgres

### ISSUE THREAD

**Issue by le30r** [DrewCarlson/kjob#84]
Have you tested this library for Postgres?

`org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ОШИБКА: ошибка синтаксиса (примерное положение: "OR")
  Позиция: 8 [statement:"INSERT OR REPLACE INTO kjobLocks VALUES (:id, :updatedAt, :expiresAt)", arguments:{positional:{}, named:{id:d3873bfc-3692-443f-83dc-4a029df84809,expiresAt:1678040488357,updatedAt:1678040188357}, finder:[]}]`

Looks like Postgres is missing the _OR REPLACE INTO statement_

**Comment by DrewCarlson** [comment]
I've updated the queries and test suite for Postgres and Mysql.  Try the latest SNAPSHOT build and let me know if you have any further issues.

**Comment by DrewCarlson** [comment]
Note the table schema was changed and there is no migration provided so you must manually drop any `kjob` related tables before using the new version.

**Comment by le30r** [comment]
Great, I just tested it and it works!

**Comment by DrewCarlson** [comment]
Thanks for confirming.  [`v0.6.0`](https://github.com/DrewCarlson/kjob/releases/tag/v0.6.0) is now available with the related fixes.
